### PR TITLE
sdl schema support

### PR DESCRIPTION
**Pull request by vasilich6107**
This is a draft PR. There are a lot to improve here)
Addresses #61

### CODE REVIEW

**Comment by comigor** [comment]
Uuuh that's nice! I'll try it soon!

**Comment by vasilich6107** [comment]
This PR is now ready for review.
I merged changes from #83 as far as there was no additional tests I'm not sure whether I did not break something)

**Comment by vasilich6107** [comment]
I have an issues with this kind of a query - https://tppr.me/zXdNj

**Comment by vasilich6107** [comment]
@comigor fixed and added tests
Please check for implementation details https://github.com/comigor/artemis/compare/af368c84c9c45a9947cedeaac60c589ed3b91dbc..f92ad672643108477459f6fefb54d0d15e2adb1e

**Comment by vasilich6107** [comment]
Reverted back that changes)
It will be to much for this PR to fix that issue
I will continue with it after this PR will be merged

**Comment by vasilich6107** [comment]
Ready to merge :-)

**Comment by comigor** [comment]
@vasilich6107 I'll try to test it against some internal projects today/tomorrow. Sorry about taking it too long!

**Comment by vasilich6107** [comment]
Thanks so much!
I've got an email that our next project will use Flutter and we need a good graphql support)
Awaiting for results of your tests.

**Comment by vasilich6107** [comment]
It you find any issues please post here some samples so I can check, fix and cover with tests

**Comment by comigor** [comment]
@vasilich6107 Just added a test reproducing an issue I've found (there's more, and I'm trying to create reproducible examples for them too).

**Comment by vasilich6107** [comment]
This helps a lot!

**Comment by comigor** [comment]
Actually I think the only issue is that the first `parentType` should be either Query or Mutation root, and it's not the case as-of-now.

**Comment by comigor** [comment]
Just commited a fix, let me know what you think while I'm testing it against my internal projects again.

**Comment by comigor** [comment]
Just checked it and everything is working fine! 🎉 So it's just a matter of fixing those tests and merge this PR.

**Comment by vasilich6107** [comment]
Got it - so I'll wait for your fix)

**Comment by vasilich6107** [comment]
Hooray  🎉 it works!

**Comment by vasilich6107** [comment]
It seems that we do not need that `FieldDefinitionVisitor`

**Comment by comigor** [comment]
As 4.0.0 is a pretty recent version, I'm leaning towards just releasing it as 5.0.0 without beta (as we don't plan to revert).

Meanwhile, given the discussion on https://github.com/comigor/artemis/pull/86 (and DM others have sent me), I'm probably opening a PR to (optionally) remove the pathes on generated classes.

**Comment by vasilich6107** [comment]
Ok. 
Let it be 5.0.0

**Comment by comigor** [comment]
Let's do this!

**Comment by comigor** [comment]
I've found another issue: some input objects are not being generated properly :(
Creating a test case and looking into it.

**Pull request merged**
