### PR TITLE
Feat/exception fragment glob and query fragments

### PR DESCRIPTION
**Pull request by vasilich6107**
Added the exception for the case when `fragment_glob` leads to query files fragments ignore.

### CODE REVIEW

**Comment by comigor** [comment]
@vasilich6107 Hmm, I got the point in doing this (to not have to handle fragments with duplicated names) but I feel the use case of having fragments on the same file as the query is rather common.

**Comment by vasilich6107** [comment]
Currently we ignore the fragments inside files if fragment_glob specified as stated in the docs)
I decided to notify the user about this before the unexpected error occurs

**Comment by vasilich6107** [comment]
I’ll write a test to illustrate what I’m talking about

**Comment by vasilich6107** [comment]
To illustrate the case I created #135 

I created a test with query that has everything to generate types inside. Added one irrelevant fragment to common fragment file + used `fragments_glob`.
https://github.com/comigor/artemis/pull/135/files#diff-c0d0e6685d31d7bac609aeecb0e78277R50

You can see that this test fails as far as in case of `fragments_glob` local fragments are ignored due to this place in code
https://github.com/comigor/artemis/blob/master/lib/generator.dart#L102

If I make file with fragments empty - test will ran correctly. So this PR meant to provide an descriptive exception to make user know what caused the error instead of `Bad state: no element`

**Pull request merged**
