### PR TITLE
fix custom scalar - incorrect 'fromGraphQL' string

### PR DESCRIPTION
**Pull request by babaker5755**

### CODE REVIEW

**Comment by babaker5755** [comment]
Was having trouble getting custom scalars to work. I found that it was generating the jsonKey wrong. My fix just ensures the generated format is  
`fromGraphQL${graphqlTypeSafeStr}ToDart$dartTypeSafeStr`
 instead of 
`fromGraphQL${dartTypeStr}ToDart$dartTypeSafeStr`

**Comment by vasilich6107** [comment]
Hi. Thanks for your PR. All the things happens in `beta` branch. Check if the beta has the same issue. If yes - could you rebase your PR onto beta branch?

**Comment by vasilich6107** [comment]
It seems that this was fixed in beta
https://github.com/comigor/artemis/blob/beta/lib/generator.dart#L361

**Comment by babaker5755** [comment]
I see that now, thanks for your help

**Pull request closed without merging**
