### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by msal4**
**Make sure you're opening this pull request pointing to beta branch!**

### CODE REVIEW

**Comment by comigor** [comment]
Hello @msal4, thanks for the contribution!

Could you update both `pubspec.yaml` and `CHANGELOG.md` files as well for this PR to be merged? Thanks!

**Comment by msal4** [comment]
@comigor something like this?

**Comment by comigor** [comment]
Yes, thank you!

**Comment by msal4** [comment]
my pleasure

**Pull request merged**
