### PR TITLE
Refactor how Artemis processes code

### PR DESCRIPTION
**Pull request by comigor**
This version completely refactors how Artemis generate code (by finally
using the implementation of visitor pattern provided by `gql`). On top of that,
I've decided to do other major breaking changes to make code cleaner and more
maintainable. Listed:
- `add_query_prefix` doesn't exist anymore (it's now the default to generate
  classes with its "path" from the query), e.g., this query's `city` field will
  be typed as `CityName$QueryRoot$User$Address$City`:
  ```graphql
  query city_name {
    user {
      address {
        city {
          name
        }
      }
    }
  }
  ```
  This change was also done to tip users to NOT use those generated queries
  directly on their code, to avoid coupling them to your business logic.
- `custom_parser_import` was moved to inside a ScalarMap, and
  `use_custom_parser` was removed.
- `resolve_type_field` option was renamed to `type_name_field`, as `__typename`
  is the correct field name (by GraphQL spec).
- Classes generated for mutation will have a `Mutation` suffix, as queries
  already have `Query` suffix.
- Change pre-generation data classes constructors to named parameters, so if
  you're using `GraphQLQueryBuilder.onBuild`, it will break.

And also:
- Add more logs and errors while generating code, to help debugging.
- Add more/refactor tests.
- Add a GitHub example.

TODO:
- [ ] clean options?
- [ ] prefix every class with `$` (?)
- [ ] refactor class naming variables
- [ ] review readme and changelog

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hmm, it seems that this changes will require to start the sdl schema support from scratch...

**Comment by vasilich6107** [comment]
`CityName$QueryRoot$User$Address$City` - this approach will lead to the class duplications.
If I have queries like 

```
voyages(pagination: $input) {
            voyage {
                arrival  {
                    id
                    name
                    type
                }
                departure {
                    id
                    name
                    type
                }               
            }
    }
```

and

```
searchDestinations() {
        destinations {
            id
            name
            type
        }
    }
```

They all use the same type 

```
type Destination {
  id: ID!
  name: String!
  type: DestinationType!
}
```

I will get three identical classes
`Voyages$QueryRoot$Voyage$Arrival`
`Voyages$QueryRoot$Voyage$Departure`
`SearchDestinations$QueryRoot$Destination`

**Comment by comigor** [comment]
Thank for taking a look at this @vasilich6107!

I was thinking about merging this on this week on a separate artemis folder, and keep the two implementations working, but it'd be so much pain to maintain the two. So I'll probably just do this breaking change at once.

But do you think this would break the sdl support? Did you plan to replace the introspection or keeping both?

About the classes creation, that's a tradeoff we need to be conscious about: either we use the same class for the three or we generate one class for each (even being exactly the same). As I could query a field in one of them but not in the other, I've opted for creating a class for each one. Does that make sense?

**Comment by vasilich6107** [comment]
I'm ok to start from scratch :-)
I have already started actually.
But let's try to avoid huge refactoring during several next weeks ;-)

**Comment by vasilich6107** [comment]
> About the classes creation, that's a tradeoff we need to be conscious about: either we use the same class for the three or we generate one class for each (even being exactly the same). As I could query a field in one of them but not in the other, I've opted for creating a class for each one. Does that make sense?

This approach definitely makes sense. We could also recommend to use `fragments` for the same selections and relay on fragment name to generate corresponding classes.

**Comment by comigor** [comment]
>We could also recommend to use fragments for the same selections and relay on fragment name to generate corresponding classes.

Definitely! As fragments are generated as mixins they abstractely can be used in the same way.

**Comment by vasilich6107** [comment]
I see that you introduced test generator helper.
Previously I had an option to debug tests from `AndroidStudio` - https://tppr.me/GniMb

Now I have an option to debug the whole group only - https://tppr.me/VQzPt and https://tppr.me/qTDz6

**Comment by comigor** [comment]
Hmm, yeah, that's true, the same happenened to me on VSCode (because it won't detect `testGenerator` as an known runner). That's why I've put `group` encapsulating each `testGenerator`.

This approach helped to reduce a lot of boilerplate of each test and made it easier to separate them in files.

**Comment by vasilich6107** [comment]
Test generator slightly updated
```
import 'dart:convert';

import 'package:artemis/builder.dart';
import 'package:artemis/generator/data.dart';
import 'package:artemis/schema/graphql.dart';
import 'package:build/build.dart';
import 'package:build_test/build_test.dart';
import 'package:logging/logging.dart';
import 'package:meta/meta.dart';
import 'package:test/test.dart';

const IS_DEBUG = true;

String jsonFromSchema(GraphQLSchema schema) => json.encode({
      'data': {'__schema': schema.toJson()}
    });

void debug(LogRecord log) {
  if (IS_DEBUG) print(log);
}

testGenerator({
  @required String query,
  @required LibraryDefinition libraryDefinition,
  @required String generatedFile,
  GraphQLSchema typedSchema,
  String stringSchema,
  bool generateHelpers = false,
  Map<String, dynamic> builderOptionsMap = const {},
  Map<String, dynamic> sourceAssetsMap = const {},
}) async {
  assert((typedSchema ?? stringSchema) != null);
  final schema = stringSchema ?? jsonFromSchema(typedSchema);

  final anotherBuilder = graphQLQueryBuilder(BuilderOptions({
    if (!generateHelpers) 'generate_helpers': false,
    'schema_mapping': [
      {
        'schema': 'api.schema.json',
        'queries_glob': '**.graphql',
        'output': 'lib/query.dart',
      }
    ],
    ...builderOptionsMap,
  }));

  anotherBuilder.onBuild = expectAsync1((definition) {
    if (IS_DEBUG) print(definition);
    expect(definition, libraryDefinition);
  }, count: 1);

  return await testBuilder(
    anotherBuilder,
    {
      'a|api.schema.json': schema,
      'a|query.graphql': query,
      ...sourceAssetsMap,
    },
    outputs: {
      'a|lib/query.dart': generatedFile,
    },
    onLog: debug,
  );
}

```

**Comment by vasilich6107** [comment]
```
void main() {
  group('On enums', () {
    test(
        'Enums can be part of queries responses',
        () async => testGenerator(
              query: query,
              libraryDefinition: libraryDefinition,
              generatedFile: generatedFile,
              typedSchema: schema,
            ));
  });
}

```

**Comment by vasilich6107** [comment]
Those ^^^^^ changes helped to get back an ability to run tests independently
https://tppr.me/zmLE9

**Comment by comigor** [comment]
That makes sense! I'm adding you as a [collaborator](https://github.com/comigor/artemis/invitations), I'll appreciate if you could commit those changes on this branch.

**Comment by vasilich6107** [comment]
Great! I'll take a lunch and then I'll update all the tests.

**Comment by vasilich6107** [comment]
I'm actively working on SDL schemas.
The tests left to fix are - aliases, custom scalars, fragments, interfaces, mutation and unions)

**Comment by comigor** [comment]
There's no rush! Actually I was thinking about merging this already, what do you think?

**Comment by vasilich6107** [comment]
Sure, let’s merge this PR

**Comment by vasilich6107** [comment]
I assume my SDL PR will live some time in draft stage cause currently the code “just works”)
May be it will be reasonable to release it under beta tag...

**Comment by comigor** [comment]
Sure, I'm gonna ship this as 4.0.0 and work on having a parallel beta branch to explorations.

**Pull request merged**
