### PR TITLE
Bugfix/hide multiple warnings under verbose

### PR DESCRIPTION
**Pull request by vasilich6107**
Warming up with simple fix for #119

### CODE REVIEW

**Comment by vasilich6107** [comment]
One moment, I'll fix the tests)

**Comment by vasilich6107** [comment]
Could you help me with test error?
I updated the version in changelog and in `pubspec.yaml`

**Comment by comigor** [comment]
Yeah, it seems fine, I think the custom script has break again 🤦‍♂️

**Comment by vasilich6107** [comment]
May be the reason that I jumped from 6.0.4 to 6.0.6?
Cause you already used 6.0.5...

**Comment by comigor** [comment]
I don't think so, I've merged the v6.0.5 and rebased here. Retrying the test, if it didn't work I'll debug the script

**Comment by comigor** [comment]
I hate the fact how barely testable GitHub Actions are. I'm gonna remove them for now and merge your PR and try to fix in another branch.

**Comment by comigor** [comment]
Nah, can't do that because beta branch pipeline will fail as well. I'm going to separate the action on a folder of its own and go from there, I'll make sure this PR reach beta asap

**Comment by vasilich6107** [comment]
ok)

**Pull request merged**
