### PR TITLE
Add test for list input

### PR DESCRIPTION
**Pull request by amadeu01**
The following test fails without #24 

But, I was expecting the following generated code:

```dart
class SomeQueryArguments extends JsonSerializable with EquatableMixin {
  SomeQueryArguments({this.ints});
   factory SomeQueryArguments.fromJson(Map<String, dynamic> json) =>
      _$SomeQueryArgumentsFromJson(json);
   final int ints;
   @override
  List<Object> get props => [ints];
  Map<String, dynamic> toJson() => _\$SomeQueryArgumentsToJson(this);
}
```

have `List<int>` instead of `   final int ints;`

cc: @klavs

### CODE REVIEW

**Comment by amadeu01** [comment]
It was expected that the test fails with the error report in #20 

image

**Comment by comigor** [comment]
Nice! Thank you!

**Comment by amadeu01** [comment]
@comigor I don't know how to rerun tests but after `1.0.2` it should pass on the test

**Comment by comigor** [comment]
@amadeu01 could you try to rebase your branch? Tests would run again after that.

**Comment by comigor** [comment]
I've discovered I can do that! Thanks again!

**Pull request merged**
