### PR TITLE
Long naming improvements

### PR DESCRIPTION
**Pull request by vasilich6107**
It is a continuation of PR #86

### CODE REVIEW

**Comment by vasilich6107** [comment]
The first commit addresses enum naming.
As far as graphql docs states

`Input types can't have fields that are other objects, only basic scalar types, list types, and other input types.`(https://graphql.org/graphql-js/mutations-and-input-types/) I will apply the same approach for input types naming.

Does this sound good for you @comigor?

**Comment by comigor** [comment]
Yes, I think it does!

I agree with having enums (as you've said they're common to all schema) as well as input objects to not have prefixes. Let's call then "canonical" objects, as their generated classes are exactly the same as defined in schema.

Regular objects are generated based on the query, so we can't use their canonical interfaces (as it'd probably implement more fields than the ones you're requesting on the query, and if the field was required you can't just omit them (if you'd be using the canonical class)), and that's why the pathed named came into play: to avoid lots of corner cases when trying to use the same name.

However, by putting a path on all generated classes, the output is currently too verbose to deal with it friendly: even though you have an adapter function converting an instance of a generated class to an internal (business) class of the same content, this adapter function still need to use those long names.

Some people reached me to include a flag to (optionally) remove the path from the generated names: as this would make it easier for those cases. I'll begin this implementation on this PR, as this would be another major bump already (😞).

**Comment by comigor** [comment]
Update: well, even this pathed naming approach has corner cases. If the path to the same object forks, but use the same classes on both forks, it'll be unable to generate two (or more) classes with the same name: https://github.com/comigor/artemis/issues/91

One approach to solve this would be change the pathes of the names of each field instead of the names of the types of each field, I think I'll change this on this same PR as well (to avoid this  kind of problem).

**Comment by comigor** [comment]
@vasilich6107 Another thing that I'm thinking right now is that those "canonical" objects ideally would be generated once for each schema (so input objects and enums would be generated only once and reused through all queries/mutations).

I'm thinking on another major refactor here: when configuring artemis, one would write something like that:
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: graphql/schema1/schema.graphql
              fragments_glob: graphql/schema1/**.fragments.graphql
              canonical_output: lib/generated/schema1/canonical.dart
              queries:
                - glob: graphql/schema1/query01.graphql
                  output: lib/generated/schema1/query01.graphql.dart
                - glob: graphql/schema1/query02.graphql
                  output: lib/generated/schema1/query02.graphql.dart
            - schema: graphql/schema2/schema.graphql
              canonical_output: lib/generated/schema2/canonical.dart
              queries:
                - glob: graphql/schema2/*.query.graphql
                  output: lib/generated/schema2/queries.graphql.dart
```
So we'd have a canonical output for each query, allowing queries to reuse it. What do you think?

**Comment by vasilich6107** [comment]
Technically it could be useful case.
I had some thoughts about this approach. 
I came to conclusion that the easiest approach is to generate all 'output' into one file. As far as all the code is `// GENERATED CODE - DO NOT MODIFY BY HAND` there is no much profit on splitting on separate files. 
We also have a good code completion and precise 'jump to source' features.

My ideal builder config looks like this 

```
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - my.schema.json
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: my.schema.json
              queries_glob: graphql/*.graphql
              output: lib/graphql_api.dart
``` 

Something like - `Configure one time and let artemis do his job`

**Comment by comigor** [comment]
Another thing that I have [in mind](https://github.com/comigor/artemis/issues/93#issuecomment-590173419) is letting user choose want kind of naming system they want (and be aware of the drawbacks of each one). I'm thinking about something like:
- **pathedWithTypes**: default, where the names of previous types are used as prefix of the next class. Eg. `QueryName$QueryRoot$Pokemon$Pokemon`
- **pathedWithFields**: the names of previous fields are used as prefix of the next class. Eg. `QueryName$QueryRoot$Charmander$Evolutions`
- **simple**: considers only the actual GraphQL class name. This will probably lead to duplication and an Artemis error unless user uses aliases. Eg. `Pokemon`

Given this, I would like to have the possibility to separate each class individually for when user wants to (and can) use "simple" naming schema, making the generated code way cleaner: some people reached me to say that, even using adapters classes, the inability to remove pathed classes names is a major annoyance.

**Comment by vasilich6107** [comment]
Currently we are on the way of solving the naming issue. If there will be some unresolvable conflicts we could think about this options. 
All of my thoughts are aligned with KISS principle - less options produces less code, less docs, less testing, less bugs and so on. I understand that this also gives less flexibility.

**Comment by comigor** [comment]
I get you. Let's solve the naming issue and in the future I can think about the change I've mentioned.
I'm just concerned with the number of major bumps (breaking changes) this lib has receiving lately. And every change like this produces another one.

**Comment by vasilich6107** [comment]
We could gather all the changes under the `beta.X` versioning)

**Comment by comigor** [comment]
>We could gather all the changes under the `beta.X` versioning

Yes, I'll setup another branch/pipeline to it.

Either way, the current "**pathedWithTypes**" has a lot of corner cases. Whay do you think about implementing and making **pathedWithFields** the default? I've just added tests for this naming strategy so we can search for other corner cases.

**Comment by vasilich6107** [comment]
I'm looking through the tests and schemas and trying to determine the common namin strategy

**Comment by vasilich6107** [comment]
Interesting case to test against)

```
type Employee implements Node {
  id: ID! @fake(type: uuid)
  firstName: String @fake(type: firstName, locale:en_CA)
  lastName: String @fake(type: lastName, locale:en_CA)
  address: String @fake(type:streetAddress, options: { useFullAddress: true })
  subordinates: [Employee!] @listLength(min: 0, max: 3)
  company: Company
}
```

```
fragment EmployeeFull on Employee {
    address
    company {
        ...CompanyFull
    }
    firstName
    id
    lastName
    subordinates {
        ...EmployeeFull
    }
}
```

**Comment by comigor** [comment]
Yeah, fragment spreads must not form cycles: https://spec.graphql.org/June2018/#sec-Fragment-spreads-must-not-form-cycles

**Comment by vasilich6107** [comment]
I have a suggestion on the naming scheme.

First of all lets start from the types that graphql gives us - based on https://graphql.org/learn/schema/#type-system

Scalar types
Enumeration types
Input types 
Query and Mutation type

Object types
Interfaces 
Union types

First three types are pretty straightforward to deal with.
	Scalar types
	Enumeration types
	Input types 

Scalar types are mapped directly to dart types or to external implementation(see the scalar_mapping option) in case of custom scalar types.
Enum and input types has unique name across the schema so we transfer the name one to one(with some capitalisation) from schema to dart code. 

In case of query and mutation types we name the class according to query name in definition with corresponding prefix Query or Mutation: 
query companyData {
  allCompanies {
    name
  }
}

will generate CompanyDataQuery class

The main challenge is to define suitable naming schema for object types. Also for interfaces and unions.

Let’s start from simple objects. We could query the object in three different ways
- directly full object
- directly part of object
- full or part of the object via one or many fragments mixing in inline fragments

In case of “directly full object” - we can detect that we are querying the the whole object by comparing it to the object defined in schema.
In this case we are happily create a dart class with the same name.

In case “directly part of object” we fallback to the `joinName` naming path. Cause we could not easily define a naming schema for this case.

In case if we use fragments to query the object we can choose the next path:
- in case of mixing fragments, inline fragments and direct field list we can check whether a requested subset of fields matches with full object and create the class with the name of that object itself instead of mixing the fragment names

Example how the three field object could be requested in funny way:
```
type  Employee {
    firstName
    id
    lastName
} 

fragment FirstNameFragment on  Employee {
	firstName
}

query AbstractData {
	data {
		id # direct query
		… FirstNameFragment # query by fragment
		… on Employee { # query by inline fragment
			lastName
		}
	}
} 
```

- create object with the same as fragment name  
- create an object with concatenated fragment names(in case if more then one fragment used to query one specific object)
- If fragments mixed with inline fragments and direct field list and does not match a full subset from object we will fallback to the `joinName` naming schema 

In next comment I will describe the approach for interfaces.

**Comment by vasilich6107** [comment]
**Unions**

We can query unions in two ways
- with fragments
- with inline fragments 

First of all we analyse whether the subset of fragments covers the one of union object. If it does - make a class with the same name as union.
If all the selection represented by named fragments - make a class of concatenated fragment names
If selection does not cover whole object and contains inline fragments - fallback to the `joinName` scheme

**Comment by vasilich6107** [comment]
Interfaces

Simple example
`employee` returns `Node` interface which is implemented by `Employee` and `Company` types

```
query EmployeeData {
  employee(id: 5) {
    id
    ...EmployeeFirstName
    ... on Employee {
      address
    }
    ... on Company {
      name
    }
  }
}
```

We can query the interface by:

First we check whether we query the whole subset of fields from interface and corresponding objects.
If we do - name the interface and all the classes by corresponding type names

Otherwise - fallback to the `joinName` strategy for the interface class name.

Next we look to the corresponding objects.
- If we query all the fields from the object either directly or by fragments/inline fragments - we can name the classes the same as corresponding types in schema
- If we query the object by named fragment(s) we can name the class as FragmentName or ConcatenatinOfFragmentNames
- If we query the object by mix of named fragments and inline fragments(who knows why) we fallback to the `joinName` strategy

**Comment by vasilich6107** [comment]
@comigor I finished a draft proposal for naming strategy.
I'll reread it later and try to reimagine one more time.
From my current perspective this approach could free us from `long naming issue` and give the users of `artemis` a good level flexibility.

This proposal could become a basement for documentation.

Also in case of fallback to the `joinName` approach we could make a notice in console.

**Comment by comigor** [comment]
Let me think about this for a couple of days!

**Comment by comigor** [comment]
First of all, @vasilich6107, thank you so much for putting this amount of effort  helping on this lib!

So, about scalar/enum/input I think we all agree they should be generated as canonical (be generated with all their fields). In the case of a field addition to those types, the class will be regenerated with this field and nothing would break.

>In case of “directly full object” - we can detect that we are querying the the whole object by comparing it to the object defined in schema.
In this case we are happily create a dart class with the same name.

I don't fully agree in having it being generated as canonical even if we're retrieving all its fields. Let's say we have the following schema:

```graphql
type Employee {
    id: ID!
    firstName: String!
    lastName: String!
}
```

And the following query:
```graphql
query employeeABC {
    employee(id: "abc") {
        id
        firstName
        lastName
    }
}
```

If we generate the `Employee` type as canonical (generate it as a `Employee` name Dart class), what would happen if the schema on backend changes? Let's say the schema now have an optional `middleName`. If we run artemis again, the generated class would have its name changed to `EmployeeABC$EmployeeQuery$Employee`, and that would break the user's code.

```graphql
type Employee {
    id: ID!
    firstName: String!
    lastName: String!
}
```

>In case “directly part of object” we fallback to the joinName naming path. Cause we could not easily define a naming schema for this case.

Even so, the actual **pathedWithTypes** `joinName` won't generate unique classes (as seen on https://github.com/comigor/artemis/issues/93 and other closed issues). That's why I've suggested (and implemented) the **pathedWithFields** approach on https://github.com/comigor/artemis/pull/96.

---

About interfaces, the same concern about generating a canonical object applies: if the schema changes, it would generate a breaking change for the user. Also, we can't generate just only class for all usages of the interface through the query, because each usage of it can query a different subset of fields.

Unions follow the same principle, as the fragments used to query them could change.

---

And finally about fragments, the inline could be just expanded into the selection set (as they're not nameable). For named fragments, I like the possibility of having them generated as mixins because one could query objects from different query locations even though we're not generating the same name for classes:

```graphql
type Employee {
    id: ID!
    firstName: String!
    lastName: String!
    boss: Employee
}
```

With the query:
```graphql
fragment named_employee on Employee {
    ...firstName
    ...lastName
}

query employeeABC {
    employee(id: "abc") {
        id
        ...named_employee
        boss {
            ...named_employee
        }
    }
}
```

Would allow us to concat both `EmployeeABC$EmployeeQuery$Employee` and `EmployeeABC$EmployeeQuery$Employee$Employee` into a single `List<NameEmployeeMixin>` for name listing purposes.

---

So, my principal concern lies on this breaking change for the user on their own code when some query or schema changes. Another (minor, but still relevant) concern with this approach is that a lot of forks on the code would be needed (to generate the classes names differently based on their selection set), making the whole code more difficult to grasp.

**Comment by vasilich6107** [comment]
Hi! I will look through the #96
If we both ok with `scalar/enum/input` are we going to merge this PR or you will implement this in #96?

RAW THOUGHTS(I will think deeper about it during the day)
I understand your concerns. In case of rapid schema changes the class names could highly change)
Happily we have an awesome linter that will reveal all the errors in case of naming changes...
One of the possible solutions could be the alias mapping in which user could specify the shorten names for the classes...

I will add more thoughts later)

**Comment by comigor** [comment]
So, linter would pop an error for us but I'd rather not having breaking changes on the code on a schema modification for the hassle it'd generate every time you'd change something on your code. 

Also, borrowing the KISS principle you've mentioned earlier, I don't think the code for dealing with checking/generation of canonical given their selection set would be easy to maintain, and maybe it don't add much to the user given the current options.

Alias mapping could be a neat possibility to have, but it'd probably be ideal to be used on top of other naming abstraction, as manually map all types would be tedious.

And yeah, actually the naming system is kinda plugabble right now (where `joinedName` and `_stringForNaming` basically take care of everything to build the path), and that's why I've created a new configuration.

I'm confident with https://github.com/comigor/artemis/pull/96

**Comment by vasilich6107** [comment]
So I will close this PR in favor of #96 ?

**Comment by comigor** [comment]
Yes, as you've already seen, I've cherry picked the enum/input object changes there.

**Pull request closed without merging**
