### PR TITLE
perf: Improved canonical visitor performance

### LINKED ISSUE #319: it is slow that generate code
In large schema (such as 33891 lines), it takes 8 minutes when run `flutter pub run build_runner build`

```
ryicoh@ryicohs-MacBook-Air uiv2 % wc ./lib/graphql/hasura_schema.graphql
   33891   76551  784987 ./lib/graphql/hasura_schema.graphql
```

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 665ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 75ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 393ms

[INFO] Running build...
[INFO] 8m 30s elapsed, 0/1 actions completed.
[WARNING] No actions completed for 8m 30s, waiting on:
  - artemis:artemis on lib/$lib$

[INFO] 8m 33s elapsed, 1/2 actions completed.
[INFO] Running build completed, took 8m 34s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 34ms

[INFO] Succeeded after 8m 34s with 4 outputs (4 actions)
                      --------
```

### PR DESCRIPTION
**Pull request by Luke265**
## What does this PR do/solve?
Fixes #319

### CODE REVIEW

**Comment by vasilich6107** [comment]
@Luke265 what's the result of this improvement for your case?

**Comment by vasilich6107** [comment]
`logFn` contains this check inside
https://github.com/comigor/artemis/blob/e1a213400a84dc44eb830bd90f26efe12bb2874c/lib/generator/helpers.dart#L192

**Comment by Luke265** [comment]
> 
> 
> @Luke265 what's the result of this improvement for your case?

Before 163 205 ms (~3 minutes), ~13 000 lines in schema file
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 408ms

[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 996ms

[WARNING] The package `____` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 814ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[WARNING] artemis:artemis on lib/$lib$:
[DEBUG] Profiling schema.accept(canonicalVisitor); started
[WARNING] artemis:artemis on lib/$lib$:
[DEBUG] schema.accept(canonicalVisitor); executed within 163205 ms
[INFO] 2m 46s elapsed, 0/1 actions completed.
[WARNING] No actions completed for 2m 46s, waiting on:
  - artemis:artemis on lib/$lib$

[INFO] 2m 47s elapsed, 27/29 actions completed.
[INFO] 2m 48s elapsed, 27/29 actions completed.
[INFO] 2m 49s elapsed, 27/29 actions completed.
[INFO] 2m 51s elapsed, 27/29 actions completed.
[INFO] 3m 0s elapsed, 28/29 actions completed.
[INFO] 3m 1s elapsed, 86/87 actions completed.
[INFO] Running build completed, took 3m 1s  

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 48ms

[INFO] Succeeded after 3m 1s with 5 outputs (117 actions)
```

After 16 ms, huge improvement
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 428ms

[WARNING] The package `____` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 64ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 756ms

[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 4ms

[INFO] Generating build script...
[INFO] Generating build script completed, took 100ms

[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 921ms

[WARNING] The package `land_lord` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 822ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[WARNING] artemis:artemis on lib/$lib$:
[DEBUG] Profiling schema.accept(canonicalVisitor); started
[WARNING] artemis:artemis on lib/$lib$:
[DEBUG] schema.accept(canonicalVisitor); executed within 76 ms
[INFO] 2.6s elapsed, 0/1 actions completed.
[INFO] 3.6s elapsed, 27/29 actions completed.
[INFO] 4.7s elapsed, 27/29 actions completed.
[INFO] 5.7s elapsed, 27/29 actions completed.
[INFO] 7.4s elapsed, 27/29 actions completed.
[INFO] 14.5s elapsed, 28/29 actions completed.
[INFO] 15.5s elapsed, 86/87 actions completed.
[INFO] Running build completed, took 15.6s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 54ms

[INFO] Succeeded after 15.7s with 5 outputs (117 actions)
```

> 
> 
> `logFn` contains this check inside
> 
> https://github.com/comigor/artemis/blob/e1a213400a84dc44eb830bd90f26efe12bb2874c/lib/generator/helpers.dart#L192

Yes, I was aware of that. But checking whether to log or not, before function call is a tiny bit more performant too. But the real culprit is `properties.addAll`. It is super slow, not sure why exactly. Maybe because of list growth, or internal type checks.

**Comment by vasilich6107** [comment]
Are you sure that omitting one fiction call could result in 10 times better performance?
It seems like result of the second run of generation with the same input(which is fast due to the caching).

**Comment by vasilich6107** [comment]
Could you attach your schema?

**Comment by Luke265** [comment]
> 
> 
> Are you sure that omitting one fiction call could result in 10 times better performance?
> It seems like result of the second run of generation with the same input(which is fast due to the caching).

I am also aware about caching. Yes, if queries and mutations are not changed, since last build, then second run would be fast without these changes. But I've changed some queries every time before building to avoid caching. So yes, I'am sure that this tiny change improves performance.

> 
> 
> Could you attach your schema?

https://pastebin.com/VZEZd4Yg

This schema is auto generated with [typegraphql-prisma](https://www.npmjs.com/package/typegraphql-prisma)

**EDIT:** Oh, and I benchmarked `visitInputObjectTypeDefinitionNode` function calls. Before the changes single function call takes 20-60 ms. After these changes much faster, less than 1 ms. `MappedListIterable<T, T>` conversion to `List<T>` is very slow in Dart VM, for some reason. This simple test shows that `addAll` is a lot slower than just `map` at least on my machine.

```
void main() {
  testAddAll();
  testJustMap();
}

void testAddAll() {
  final totalList = [];
  final start = DateTime.now();
  final testArray = List.filled(1000, 1);
  for (var i = 0; i < 10000; i++) {
    final arr = <int>[];
    arr.addAll(testArray.map((e) => 2));
    totalList.add(arr);
  }
  print("TestAddAll ${DateTime.now().difference(start).inMilliseconds}");
}

void testJustMap() {
  final totalList = [];
  final start = DateTime.now();
  final testArray = List.filled(1000, 1);
  for (var i = 0; i < 10000; i++) {
    final arr = testArray.map((e) => 2);
    totalList.add(arr);
  }
  print("TestJustMap ${DateTime.now().difference(start).inMilliseconds}");
}
```

**Comment by vasilich6107** [comment]
Thanks for extended explanation.
I will check your samples.
May be this will help to improve overall performance

**Comment by vasilich6107** [comment]
@Luke265 the main issue in your test is that map in itarable resolves lazily. If you add `.toList()` on your map we will get
```
TestAddAll 116
TestJustMap 107
```

**Comment by vasilich6107** [comment]
So the main idea it to make all results from canonical lazy resolvable.
I will try to do it this week

**Comment by vasilich6107** [comment]
Try `7.0.0-beta.16`

**Pull request closed without merging**
