### PR TITLE
@JsonValue() annotation to ensure case sensitive compatibility

### PR DESCRIPTION
**Pull request by parisholley**
potential fix for #122

my issue was that my nestjs/graphql setup is expecting enums to be in the same casing as the graphql schema (uppercase), but the library was camel' casing in dart, and default to that same casing when sending to the server. this PR allows dart to still use camelCase convention but post to server using a different value.

### CODE REVIEW

**Comment by comigor** [comment]
Hello @parisholley! We did this Enum change on https://github.com/comigor/artemis/pull/141, but we've just reverted it on https://github.com/comigor/artemis/pull/153, given the exact problem you've mentioned.

The work of @vasilich6107 on https://github.com/comigor/artemis/pull/146 (which I've begun to extract on https://github.com/comigor/artemis/pull/142), along with the changes he introduced on https://github.com/comigor/artemis/pull/139, will allow us to manage those naming systems easily.

Could you wait for us to merge those PR, hence allowing you to rebase this PR?

**Comment by parisholley** [comment]
Sure

**Comment by vasilich6107** [comment]
@parisholley we added `JSONValue` annotation in scope of naming refactoring.
Could you try the latest beta?

**Comment by parisholley** [comment]
beta looks good

**Pull request closed without merging**
