### PR TITLE
Change enum casing to camelCase

### LINKED ISSUE #122: Feature Request: Make enum casing configurable
Right now the enums generated by artemis are all like this: "ENUM_EXAMLE"

Im not sure if this is because of what my api is sending artemis or if artemis generally makes enums look like this. But it doesn't matter after all.

There is a package called: https://pub.dev/packages/recase

With this it could be made configurable which style enums should have.

In dart by default enums are "camelcase" ... so I think camelcase should be made default in the next major release.

### PR DESCRIPTION
**Pull request by lazylazyllama**
With this pr I added the ReCase function to change enum casing to camelcase.

I did this because camelcase is the standard casing format for enums in dart.

This fixes #122

### CODE REVIEW

**Comment by lazylazyllama** [comment]
I did not change the CHANGELOG file because I wasn't sure about which version to put in.

**Comment by lazylazyllama** [comment]
I tested it with my pretty huge project and everything is working now.

Can anyone review this please?

**Comment by vasilich6107** [comment]
We are working on naming issues in #141 #142

**Comment by lazylazyllama** [comment]
@vasilich6107 I don't really understand why you would reference pr #141 in this pr as this pr is #141 🤔

**Comment by vasilich6107** [comment]
Mistyped))) I mean #140

**Comment by comigor** [comment]
Hey @lazylazyllama,could you rebase this PR?

**Comment by lazylazyllama** [comment]
Sure :)

**Comment by comigor** [comment]
I think I won't be able to fix the tests/linter right now, but if you do it, I can merge right away!

**Comment by lazylazyllama** [comment]
I would love to do that, but right now I have no idea how the test works and which test is failing:

https://github.com/comigor/artemis/pull/141/checks?check_run_id=692958221

I don't see any errors there ... It just looks like the test just stops and says it failed .. for no reason 🤔

**Comment by comigor** [comment]
This could definitely be clearer. The linter is acusing something on the `lib/generator.dart` file:
```=== Running linter ===
lib/generator.dart```

I'll try to make actions clearer (and post the errors on the PR in the future)

**Comment by lazylazyllama** [comment]
Done :)

**Comment by comigor** [comment]
Thanks! I've just changed it to bump a minor, just to keep little tracking on breaking changes.

**Pull request merged**
