### PR TITLE
update pubspec.yaml

### PR DESCRIPTION
**Pull request by ram231**
Issue: #217

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @ram231 
The latest beta is `v6.12.3-beta.1` could you rebase your PR to avoid conflicts?

**Comment by ram231** [comment]
@vasilich6107 sorry I messed up. I'll change it to `v6.12.3-beta.1`

**Comment by ram231** [comment]
I don't know about the changelg & version. should I update it to `v6.12.4-beta.1` and add changelogs?
but on CI test, it failed because of I was using beta branch?
`Because artemis depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.`

**Comment by vasilich6107** [comment]
It is not enough to update the versions.
Project should pass the tests.

**Comment by vasilich6107** [comment]
The changelog and versions should be also updated.
6.13.1-beta.1 will be better. Cause package update could lead to unexpected behaviour on client side

**Comment by vasilich6107** [comment]
use 1.10.1 for build_runner

**Comment by ram231** [comment]
I think should close this :( I did not have time to make changes. I'm in a tight schedule with my current team, so I had to use my own fork.

**Comment by vasilich6107** [comment]
Actually you do not need your own fork just use dependency_overrides in your project to have the lib version you need

**Comment by vasilich6107** [comment]
Closing in favour of #221

**Pull request closed without merging**
